# Cleaning Automation

In [1]:
import pandas as pd

In [2]:
def remove_tuples_with_less_data(data):
    """
    Remove tuples from the DataFrame where the number of non-null values is less than the specified minimum.

    Parameters:
    - data: pandas DataFrame

    Returns:
    - pandas DataFrame with tuples removed
    """
    # Display the number of columns in the DataFrame
    num_columns = len(data.columns)
    print(f"Number of columns in the DataFrame: {num_columns}")

    # Display the DataFrame to the user
    print("\nOriginal DataFrame:")
    print(data.head(10))

    # Ask the user for the minimum non-null count
    min_non_null_count = int(input("\nEnter the minimum number of non-null values required for each tuple: "))

    # Count non-null values for each tuple
    non_null_counts = data.count(axis=1)

    # Identify tuples with less than the specified minimum non-null values
    tuples_to_remove = data[non_null_counts < min_non_null_count]

    # Display information about tuples to be removed
    print(f"\nTuples to be removed:\n{tuples_to_remove}")

    # Ask for user confirmation
    user_input = input(f"\nDo you want to remove these tuples? (yes/no): ").lower()

    if user_input == 'yes':
        # Remove the identified tuples
        data_cleaned = data.drop(tuples_to_remove.index)
        print("Tuples removed successfully.")
        return data_cleaned
    else:
        print("No tuples were removed.")
        return data


# Example usage:
# Assuming 'your_data' is your DataFrame.

# your_data = ...

# Cleaned data after removing tuples with less data
# cleaned_data = remove_tuples_with_less_data(your_data)

In [3]:
def fill_nulls_with_3m(data):
    """
    Fill null values in specified columns based on user choice (mean/median/mode).

    Parameters:
    - data: pandas DataFrame

    Returns:
    - pandas DataFrame with null values filled
    """

    # Ask the user for a list of column names to fill
    columns_to_fill = input("\nEnter a comma-separated list of column names to fill (e.g., col1, col2): ").split(',')

    # Remove leading and trailing whitespaces from column names
    columns_to_fill = [col.strip() for col in columns_to_fill]

    # Iterate over selected columns and ask the user for the filling method
    for column in columns_to_fill:
        if column in data.columns:
            # Ask the user for the filling method (mean/median/mode)
            filling_method = input(f"\nChoose filling method for '{column}' (mean/median/mode): ").lower()

            # Fill null values based on user choice
            if filling_method == 'mean':
                data[column].fillna(data[column].mean(), inplace=True)
                print(f"Null values in '{column}' filled with mean.")
            elif filling_method == 'median':
                data[column].fillna(data[column].median(), inplace=True)
                print(f"Null values in '{column}' filled with median.")
            elif filling_method == 'mode':
                data[column].fillna(data[column].mode()[0], inplace=True)
                print(f"Null values in '{column}' filled with mode.")
            else:
                print(f"Invalid filling method '{filling_method}' for '{column}'. Skipping.")

    # Display the top 10 tuples of the DataFrame after filling null values
    print("\nDataFrame after filling null values (top 10 tuples):")
    print(data.head(10))

    return data


# Example usage:
# Assuming 'your_data' is your DataFrame.

# your_data = ...

# DataFrame after filling null values based on user choice
# data_filled = fill_nulls_with_user_choice(your_data)

In [4]:
def fill_nulls_with_global_constant(data):
    """
    Fill null values in columns with around 10% null values using a global constant.

    Parameters:
    - data: pandas DataFrame

    Returns:
    - pandas DataFrame with null values filled
    """

    # Identify columns with around 10% null values
    null_percentage_threshold = 10
    columns_with_nulls = data.columns[data.isnull().mean() * 100 > null_percentage_threshold]

    if not columns_with_nulls.empty:
        # Display columns with around 10% null values to the user
        print("\nColumns with around 10% null values:")
        print(columns_with_nulls)

        # Ask the user for a global constant value
        global_constant = input("\nEnter the global constant value to fill null values in these columns: ")

        # Iterate over selected columns and fill null values with the global constant
        for column in columns_with_nulls:
            data[column].fillna(global_constant, inplace=True)
            print(f"Null values in '{column}' filled with global constant.")

        # Display the top 10 tuples of the DataFrame after filling null values
        print("\nDataFrame after filling null values (top 10 tuples):")
        print(data.head(10))
    else:
        print("\nNo columns with around 10% null values found. No null values were filled.")

    return data


# Example usage:
# Assuming 'your_data' is your DataFrame.

# your_data = ...

# DataFrame after filling null values with a global constant for columns with around 10% null values
# data_filled = fill_nulls_with_global_constant(your_data)

In [5]:
def fill_nulls_by_class_user_input(data, class_column):
    """
    Fill null values in columns based on the user's choice of attribute mean or median, by class.

    Parameters:
    - data: pandas DataFrame
    - class_column: str, the column representing the class variable

    Returns:
    - pandas DataFrame with null values filled based on user input
    """

    # Check if the specified class column exists
    if class_column not in data.columns:
        print(f"\nError: '{class_column}' not found in the DataFrame.")
        return data

    # Identify columns with null values
    columns_with_nulls = data.columns[data.isnull().any()]

    # Create a table showing null values and their percentages by class
    null_summary_table = pd.DataFrame(index=columns_with_nulls, columns=['Null Count', 'Null Percentage by Class'])

    for column in columns_with_nulls:
        null_summary_table.loc[column, 'Null Count'] = data[column].isnull().sum()

        # Create a new DataFrame for the percentage by class operation
        percentage_by_class_df = pd.DataFrame(
            data.groupby(class_column)[column].apply(lambda x: x.isnull().mean() * 100)
        ).round(2).astype(str) + '%'

        # Assign the values to the null_summary_table
        null_summary_table.loc[column, 'Null Percentage by Class'] = percentage_by_class_df.values

    # Display the null summary table
    print("\nNull Values Summary Table:")
    print(null_summary_table)

    # Ask the user for the list of columns to fill and their filling method (mean/median)
    fill_columns = input("\nEnter a comma-separated list of columns to fill (e.g., col1, col2): ").split(',')
    fill_method = input("\nEnter filling method for these columns (mean/median): ").lower()

    # Remove leading and trailing whitespaces from column names
    fill_columns = [col.strip() for col in fill_columns]

    # Iterate over selected columns and fill null values based on user input
    for column in fill_columns:
        if column in data.columns:
            if fill_method == 'mean':
                data[column] = data.groupby(class_column)[column].transform(lambda x: x.fillna(x.mean()))
            elif fill_method == 'median':
                data[column] = data.groupby(class_column)[column].transform(lambda x: x.fillna(x.median()))
            else:
                print(f"Invalid filling method '{fill_method}' for '{column}'. Skipping.")

            print(f"Null values in '{column}' filled based on {fill_method} by class.")

    # Display the top 10 tuples of the DataFrame after filling null values
    print("\nDataFrame after filling null values (top 10 tuples):")
    print(data.head(10))

    return data

# Example usage:
# Assuming 'data' is your DataFrame and 'class_column' is the column representing the class variable
# fill_nulls_by_class_user_input(data, 'class_column')

In [6]:
import pandas as pd

def remove_columns_with_high_null_percentage(data):
    """
    Remove columns with null values exceeding the specified threshold percentage.

    Parameters:
    - data: pandas DataFrame

    Returns:
    - pandas DataFrame with columns removed
    """
    # Calculate the percentage of null values for each column
    null_percentage = (data.isnull().mean() * 100).round(2)
    print(null_percentage)
    # Specify the threshold percentage
    threshold_percentage = float(input("Enter threshold percentage: "))

    # Identify columns above the threshold
    columns_above_threshold = null_percentage[null_percentage < threshold_percentage].index.tolist()

    if columns_above_threshold:
        # Display information about columns to be removed
        print(f"\nColumns to be removed (null percentage > {threshold_percentage}%):\n{columns_above_threshold}")

        # Ask for user confirmation
        user_input = input("\nDo you want to remove these columns? (yes/no): ").lower()

        if user_input == 'yes':
            # Remove the identified columns
            data_cleaned = data.drop(columns=columns_above_threshold)
            print("Columns removed successfully.")
            return data_cleaned
        else:
            print("No columns were removed.")
            return data
    else:
        print("\nNo columns with null values exceeding the threshold found. No columns were removed.")
        return data

# Example usage:
# Assuming 'your_data' is your DataFrame.
# your_data = ...

# Cleaned data after removing columns with high null percentage
# cleaned_data = remove_columns_with_high_null_percentage(your_data)

In [7]:

def main():
    # Step 1: Take data and convert it into a DataFrame
    file_path = input("Enter the path to the CSV file: ")
    
    try:
        df = pd.read_csv(file_path)
    except FileNotFoundError:
        print(f"Error: The file '{file_path}' was not found.")
        return
    except pd.errors.EmptyDataError:
        print(f"Error: The file '{file_path}' is empty.")
        return

    # Display the original DataFrame

    # Step 2: Remove columns with high null percentage
    df = remove_columns_with_high_null_percentage(df)  # Adjust the threshold percentage as needed

    # Display the DataFrame after removing columns with high null percentage
    print("\nDataFrame after removing columns with high null percentage:")
    print(df)
    # Step 2.1: Remove tuples with less data
    df = remove_tuples_with_less_data(df)  # Adjust the minimum non-null count as needed

    # Display the DataFrame after removing tuples with less data
    print("\nDataFrame after removing tuples with less data:")
    print(df)

    

    # Initialize a loop until there are no null values
    while df.isnull().any().any():
        # Display the columns with their corresponding percentage of null values
        print("\nColumns and their percentage of null values:")
        null_percentage = df.isnull().mean() * 100
        print(null_percentage)

        print("\nNull values are present in the DataFrame.")

        # Display menu for the user to choose a method
        print("\nChoose a method to handle null values:")
        print("1. Fill with mean/median/mode")
        print("2. Fill with global constant")
        print("3. Fill by class with user input")

        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            # Step 3: Fill null values with user choice
            df = fill_nulls_with_3m(df)

        elif choice == '2':
            # Step 4: Fill null values with a global constant for columns with around 10% null values
            df = fill_nulls_with_global_constant(df)

        elif choice == '3':
            # Step 5: Fill null values by class with user input
            class_column = input("Enter the column representing the class variable: ")
            df = fill_nulls_by_class_user_input(df, class_column)

        else:
            print("Invalid choice. Please enter 1, 2, or 3.")

    # Display the final DataFrame without null values
    print("\nFinal DataFrame without null values:")
    print(df)

if __name__ == "__main__":
    main()

Enter the path to the CSV file: demographic.csv
SEQN         0.00
SDDSRVYR     0.00
RIDSTATR     0.00
RIAGENDR     0.00
RIDAGEYR     0.00
RIDAGEMN    93.39
RIDRETH1     0.00
RIDRETH3     0.00
RIDEXMON     3.56
RIDEXAGM    58.59
DMQMILIZ    38.47
DMQADFC     94.66
DMDBORN4     0.00
DMDCITZN     0.04
DMDYRSUS    81.25
DMDEDUC3    72.45
DMDEDUC2    43.30
DMDMARTL    43.30
RIDEXPRG    87.14
SIALANG      0.00
SIAPROXY     0.01
SIAINTRP     0.00
FIALANG      1.19
FIAPROXY     1.19
FIAINTRP     1.19
MIALANG     28.15
MIAPROXY    28.14
MIAINTRP    28.13
AIALANGA    37.92
DMDHHSIZ     0.00
DMDFMSIZ     0.00
DMDHHSZA     0.00
DMDHHSZB     0.00
DMDHHSZE     0.00
DMDHRGND     0.00
DMDHRAGE     0.00
DMDHRBR4     2.92
DMDHREDU     2.89
DMDHRMAR     1.21
DMDHSEDU    47.50
WTINT2YR     0.00
WTMEC2YR     0.00
SDMVPSU      0.00
SDMVSTRA     0.00
INDHHIN2     1.31
INDFMIN2     1.21
INDFMPIR     7.71
dtype: float64
Enter threshold percentage: 40

Columns to be removed (null percentage > 40.0%):
['RIDAGEMN', 'RIDEXAGM', 'DMQADFC', 'DMDYRSUS', 'DMDEDUC3', 'DMDEDUC2', 'DMDMARTL', 'RIDEXPRG', 'DMDHSEDU']

Do you want to remove these columns? (yes/no): yes
Columns removed successfully.

DataFrame after removing columns with high null percentage:
        SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0      73557         8         2         1        69         4         4
1      73558         8         2         1        54         3         3
2      73559         8         2         1        72         3         3
3      73560         8         2         1         9         3         3
4      73561         8         2         2        73         3         3
...      ...       ...       ...       ...       ...       ...       ...
10170  83727         8         2         1        26         2         2
10171  83728         8         2         2         2         1         1
10172  83729         8         2         2        42         4         4
10173  83730         8         2         1         7         2         2
10174  83731         8         2         1        11         5         6

       RIDEXMON  DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0           1.0       1.0         1  ...       1.0       3.0       4.0
1           1.0       2.0         1  ...       1.0       3.0       1.0
2           2.0       1.0         1  ...       1.0       4.0       1.0
3           1.0       NaN         1  ...       1.0       3.0       1.0
4           1.0       2.0         1  ...       1.0       5.0       1.0
...         ...       ...       ...  ...       ...       ...       ...
10170       2.0       2.0         1  ...       1.0       3.0       NaN
10171       2.0       NaN         1  ...       1.0       3.0       1.0
10172       2.0       2.0         2  ...       2.0       5.0       3.0
10173       1.0       NaN         1  ...       2.0       4.0       1.0
10174       1.0       NaN         1  ...       2.0       5.0       1.0

           WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA  INDHHIN2  INDFMIN2  \
0      13281.237386  13481.042095        1       112       4.0       4.0
1      23682.057386  24471.769625        1       108       7.0       7.0
2      57214.803319  57193.285376        1       109      10.0      10.0
3      55201.178592  55766.512438        2       109       9.0       9.0
4      63709.667069  65541.871229        2       116      15.0      15.0
...             ...           ...      ...       ...       ...       ...
10170  27141.631824  28115.568221        1       104      77.0      77.0
10171  15274.475360  16512.138781        1       107       8.0       8.0
10172  24122.248900  26902.344381        1       104       7.0       7.0
10173  25521.878546  26686.025573        2       109       6.0       6.0
10174   8930.180154   9700.873491        2       106      15.0      15.0

       INDFMPIR
0          0.84
1          1.78
2          4.51
3          2.52
4          5.00
...         ...
10170       NaN
10171      1.95
10172      3.66
10173      1.05
10174      5.00

[10175 rows x 38 columns]
Number of columns in the DataFrame: 38

Original DataFrame:
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON  DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0       1.0       1.0         1  ...       1.0       3.0       4.0
1       1.0       2.0         1  ...       1.0       3.0       1.0
2       2.0       1.0         1  ...       1.0       4.0       1.0
3       1.0       NaN         1  ...       1.0       3.0       1.0
4       1.0       2.0         1  ...       1.0       5.0       1.0
5       1.0       1.0         1  ...       1.0       4.0       3.0
6       2.0       NaN         1  ...       1.0       5.0       1.0
7       2.0       2.0         1  ...       1.0       5.0       2.0
8       NaN       2.0         1  ...       1.0       3.0       1.0
9       1.0       2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA  INDHHIN2  INDFMIN2  INDFMPIR
0  13281.237386  13481.042095        1       112       4.0       4.0      0.84
1  23682.057386  24471.769625        1       108       7.0       7.0      1.78
2  57214.803319  57193.285376        1       109      10.0      10.0      4.51
3  55201.178592  55766.512438        2       109       9.0       9.0      2.52
4  63709.667069  65541.871229        2       116      15.0      15.0      5.00
5  24978.144602  25344.992359        1       111       9.0       9.0      4.79
6  18040.818432  17913.555067        1       105      15.0      15.0      5.00
7  60325.095254  61758.654880        1       114      10.0      10.0      5.00
8  23307.675629      0.000000        2       106      15.0      15.0      5.00
9  16351.783140  17480.115175        1       112       4.0       4.0      0.48

[10 rows x 38 columns]

Enter the minimum number of non-null values required for each tuple: 6

Tuples to be removed:
Empty DataFrame
Columns: [SEQN, SDDSRVYR, RIDSTATR, RIAGENDR, RIDAGEYR, RIDRETH1, RIDRETH3, RIDEXMON, DMQMILIZ, DMDBORN4, DMDCITZN, SIALANG, SIAPROXY, SIAINTRP, FIALANG, FIAPROXY, FIAINTRP, MIALANG, MIAPROXY, MIAINTRP, AIALANGA, DMDHHSIZ, DMDFMSIZ, DMDHHSZA, DMDHHSZB, DMDHHSZE, DMDHRGND, DMDHRAGE, DMDHRBR4, DMDHREDU, DMDHRMAR, WTINT2YR, WTMEC2YR, SDMVPSU, SDMVSTRA, INDHHIN2, INDFMIN2, INDFMPIR]
Index: []

[0 rows x 38 columns]

Do you want to remove these tuples? (yes/no): yes
Tuples removed successfully.

DataFrame after removing tuples with less data:
        SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0      73557         8         2         1        69         4         4
1      73558         8         2         1        54         3         3
2      73559         8         2         1        72         3         3
3      73560         8         2         1         9         3         3
4      73561         8         2         2        73         3         3
...      ...       ...       ...       ...       ...       ...       ...
10170  83727         8         2         1        26         2         2
10171  83728         8         2         2         2         1         1
10172  83729         8         2         2        42         4         4
10173  83730         8         2         1         7         2         2
10174  83731         8         2         1        11         5         6

       RIDEXMON  DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0           1.0       1.0         1  ...       1.0       3.0       4.0
1           1.0       2.0         1  ...       1.0       3.0       1.0
2           2.0       1.0         1  ...       1.0       4.0       1.0
3           1.0       NaN         1  ...       1.0       3.0       1.0
4           1.0       2.0         1  ...       1.0       5.0       1.0
...         ...       ...       ...  ...       ...       ...       ...
10170       2.0       2.0         1  ...       1.0       3.0       NaN
10171       2.0       NaN         1  ...       1.0       3.0       1.0
10172       2.0       2.0         2  ...       2.0       5.0       3.0
10173       1.0       NaN         1  ...       2.0       4.0       1.0
10174       1.0       NaN         1  ...       2.0       5.0       1.0

           WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA  INDHHIN2  INDFMIN2  \
0      13281.237386  13481.042095        1       112       4.0       4.0
1      23682.057386  24471.769625        1       108       7.0       7.0
2      57214.803319  57193.285376        1       109      10.0      10.0
3      55201.178592  55766.512438        2       109       9.0       9.0
4      63709.667069  65541.871229        2       116      15.0      15.0
...             ...           ...      ...       ...       ...       ...
10170  27141.631824  28115.568221        1       104      77.0      77.0
10171  15274.475360  16512.138781        1       107       8.0       8.0
10172  24122.248900  26902.344381        1       104       7.0       7.0
10173  25521.878546  26686.025573        2       109       6.0       6.0
10174   8930.180154   9700.873491        2       106      15.0      15.0

       INDFMPIR
0          0.84
1          1.78
2          4.51
3          2.52
4          5.00
...         ...
10170       NaN
10171      1.95
10172      3.66
10173      1.05
10174      5.00

[10175 rows x 38 columns]

Columns and their percentage of null values:
SEQN         0.000000
SDDSRVYR     0.000000
RIDSTATR     0.000000
RIAGENDR     0.000000
RIDAGEYR     0.000000
RIDRETH1     0.000000
RIDRETH3     0.000000
RIDEXMON     3.557740
DMQMILIZ    38.466830
DMDBORN4     0.000000
DMDCITZN     0.039312
SIALANG      0.000000
SIAPROXY     0.009828
SIAINTRP     0.000000
FIALANG      1.189189
FIAPROXY     1.189189
FIAINTRP     1.189189
MIALANG     28.147420
MIAPROXY    28.137592
MIAINTRP    28.127764
AIALANGA    37.916462
DMDHHSIZ     0.000000
DMDFMSIZ     0.000000
DMDHHSZA     0.000000
DMDHHSZB     0.000000
DMDHHSZE     0.000000
DMDHRGND     0.000000
DMDHRAGE     0.000000
DMDHRBR4     2.918919
DMDHREDU     2.889435
DMDHRMAR     1.208845
WTINT2YR     0.000000
WTMEC2YR     0.000000
SDMVPSU      0.000000
SDMVSTRA     0.000000
INDHHIN2     1.307125
INDFMIN2     1.208845
INDFMPIR     7.714988
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input

Enter your choice (1/2/3): 2

Columns with around 10% null values:
Index(['DMQMILIZ', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA'], dtype='object')

Enter the global constant value to fill null values in these columns: 25
Null values in 'DMQMILIZ' filled with global constant.
Null values in 'MIALANG' filled with global constant.
Null values in 'MIAPROXY' filled with global constant.
Null values in 'MIAINTRP' filled with global constant.
Null values in 'AIALANGA' filled with global constant.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0       1.0      1.0         1  ...       1.0       3.0       4.0
1       1.0      2.0         1  ...       1.0       3.0       1.0
2       2.0      1.0         1  ...       1.0       4.0       1.0
3       1.0       25         1  ...       1.0       3.0       1.0
4       1.0      2.0         1  ...       1.0       5.0       1.0
5       1.0      1.0         1  ...       1.0       4.0       3.0
6       2.0       25         1  ...       1.0       5.0       1.0
7       2.0      2.0         1  ...       1.0       5.0       2.0
8       NaN      2.0         1  ...       1.0       3.0       1.0
9       1.0      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    3.557740
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.039312
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    1.189189
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    2.918919
DMDHREDU    2.889435
DMDHRMAR    1.208845
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    1.307125
INDFMIN2    1.208845
INDFMPIR    7.714988
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input
Enter your choice (1/2/3): 2

No columns with around 10% null values found. No null values were filled.

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    3.557740
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.039312
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    1.189189
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    2.918919
DMDHREDU    2.889435
DMDHRMAR    1.208845
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    1.307125
INDFMIN2    1.208845
INDFMPIR    7.714988
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input
Enter your choice (1/2/3): 1

Enter a comma-separated list of column names to fill (e.g., col1, col2): INDFMPIR

Choose filling method for 'INDFMPIR' (mean/median/mode): mean
Null values in 'INDFMPIR' filled with mean.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0       1.0      1.0         1  ...       1.0       3.0       4.0
1       1.0      2.0         1  ...       1.0       3.0       1.0
2       2.0      1.0         1  ...       1.0       4.0       1.0
3       1.0       25         1  ...       1.0       3.0       1.0
4       1.0      2.0         1  ...       1.0       5.0       1.0
5       1.0      1.0         1  ...       1.0       4.0       3.0
6       2.0       25         1  ...       1.0       5.0       1.0
7       2.0      2.0         1  ...       1.0       5.0       2.0
8       NaN      2.0         1  ...       1.0       3.0       1.0
9       1.0      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    3.557740
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.039312
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    1.189189
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    2.918919
DMDHREDU    2.889435
DMDHRMAR    1.208845
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    1.307125
INDFMIN2    1.208845
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input

Enter your choice (1/2/3): 1

Enter a comma-separated list of column names to fill (e.g., col1, col2): RIDEXMON,INDHHIN2,INDFMIN2,DMDHRBR4

Choose filling method for 'RIDEXMON' (mean/median/mode): mean
Null values in 'RIDEXMON' filled with mean.

Choose filling method for 'INDHHIN2' (mean/median/mode): median
Null values in 'INDHHIN2' filled with median.

Choose filling method for 'INDFMIN2' (mean/median/mode): mode
Null values in 'INDFMIN2' filled with mode.

Choose filling method for 'DMDHRBR4' (mean/median/mode): mean
Null values in 'DMDHRBR4' filled with mean.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.039312
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    1.189189
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    2.889435
DMDHRMAR    1.208845
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input
Enter your choice (1/2/3): 3
Enter the column representing the class variable: RIAGENDR

Null Values Summary Table:
         Null Count Null Percentage by Class
DMDCITZN          4       [[0.04%], [0.04%]]
SIAPROXY          1        [[0.02%], [0.0%]]
FIALANG         121       [[1.16%], [1.22%]]
FIAPROXY        121       [[1.16%], [1.22%]]
FIAINTRP        121       [[1.16%], [1.22%]]
DMDHREDU        294        [[2.9%], [2.88%]]
DMDHRMAR        123       [[1.16%], [1.26%]]

Enter a comma-separated list of columns to fill (e.g., col1, col2): DMDCITZN

Enter filling method for these columns (mean/median): mean
Null values in 'DMDCITZN' filled based on mean by class.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.000000
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    1.189189
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    2.889435
DMDHRMAR    1.208845
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input

Enter your choice (1/2/3): 3
Enter the column representing the class variable: DMDHRBR4

Null Values Summary Table:
         Null Count              Null Percentage by Class
SIAPROXY          1     [[0.0%], [0.0%], [0.03%], [0.0%]]
FIALANG         121  [[0.86%], [12.12%], [0.87%], [0.0%]]
FIAPROXY        121  [[0.86%], [12.12%], [0.87%], [0.0%]]
FIAINTRP        121  [[0.86%], [12.12%], [0.87%], [0.0%]]
DMDHREDU        294    [[0.0%], [98.99%], [0.0%], [0.0%]]
DMDHRMAR        123   [[1.26%], [4.38%], [0.77%], [0.0%]]

Enter a comma-separated list of columns to fill (e.g., col1, col2): DMDHRMAR

Enter filling method for these columns (mean/median): median
Null values in 'DMDHRMAR' filled based on median by class.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.000000
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    1.189189
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    2.889435
DMDHRMAR    0.000000
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input
Enter your choice (1/2/3): 2

No columns with around 10% null values found. No null values were filled.

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.000000
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    1.189189
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    2.889435
DMDHRMAR    0.000000
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input
Enter your choice (1/2/3): 3
Enter the column representing the class variable: RIAGENDR

Null Values Summary Table:
         Null Count Null Percentage by Class
SIAPROXY          1        [[0.02%], [0.0%]]
FIALANG         121       [[1.16%], [1.22%]]
FIAPROXY        121       [[1.16%], [1.22%]]
FIAINTRP        121       [[1.16%], [1.22%]]
DMDHREDU        294        [[2.9%], [2.88%]]

Enter a comma-separated list of columns to fill (e.g., col1, col2): FIAINTRP

Enter filling method for these columns (mean/median): mean
Null values in 'FIAINTRP' filled based on mean by class.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.000000
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    0.000000
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    2.889435
DMDHRMAR    0.000000
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input

Enter your choice (1/2/3): 1

Enter a comma-separated list of column names to fill (e.g., col1, col2): 1

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.000000
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    0.000000
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    2.889435
DMDHRMAR    0.000000
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input
Enter your choice (1/2/3): 1

Enter a comma-separated list of column names to fill (e.g., col1, col2): 1

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.000000
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     1.189189
FIAPROXY    1.189189
FIAINTRP    0.000000
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    2.889435
DMDHRMAR    0.000000
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input
Enter your choice (1/2/3): 1

Enter a comma-separated list of column names to fill (e.g., col1, col2): FIALANG,FIAPROXY,DMDHREDU

Choose filling method for 'FIALANG' (mean/median/mode): mean
Null values in 'FIALANG' filled with mean.

Choose filling method for 'FIAPROXY' (mean/median/mode): median
Null values in 'FIAPROXY' filled with median.

Choose filling method for 'DMDHREDU' (mean/median/mode): mode
Null values in 'DMDHREDU' filled with mode.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Columns and their percentage of null values:
SEQN        0.000000
SDDSRVYR    0.000000
RIDSTATR    0.000000
RIAGENDR    0.000000
RIDAGEYR    0.000000
RIDRETH1    0.000000
RIDRETH3    0.000000
RIDEXMON    0.000000
DMQMILIZ    0.000000
DMDBORN4    0.000000
DMDCITZN    0.000000
SIALANG     0.000000
SIAPROXY    0.009828
SIAINTRP    0.000000
FIALANG     0.000000
FIAPROXY    0.000000
FIAINTRP    0.000000
MIALANG     0.000000
MIAPROXY    0.000000
MIAINTRP    0.000000
AIALANGA    0.000000
DMDHHSIZ    0.000000
DMDFMSIZ    0.000000
DMDHHSZA    0.000000
DMDHHSZB    0.000000
DMDHHSZE    0.000000
DMDHRGND    0.000000
DMDHRAGE    0.000000
DMDHRBR4    0.000000
DMDHREDU    0.000000
DMDHRMAR    0.000000
WTINT2YR    0.000000
WTMEC2YR    0.000000
SDMVPSU     0.000000
SDMVSTRA    0.000000
INDHHIN2    0.000000
INDFMIN2    0.000000
INDFMPIR    0.000000
dtype: float64

Null values are present in the DataFrame.

Choose a method to handle null values:
1. Fill with user choice
2. Fill with global constant
3. Fill by class with user input

Enter your choice (1/2/3): 1

Enter a comma-separated list of column names to fill (e.g., col1, col2): SIAPROXY

Choose filling method for 'SIAPROXY' (mean/median/mode): mean
Null values in 'SIAPROXY' filled with mean.

DataFrame after filling null values (top 10 tuples):
    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0  73557         8         2         1        69         4         4
1  73558         8         2         1        54         3         3
2  73559         8         2         1        72         3         3
3  73560         8         2         1         9         3         3
4  73561         8         2         2        73         3         3
5  73562         8         2         1        56         1         1
6  73563         8         2         1         0         3         3
7  73564         8         2         2        61         3         3
8  73565         8         1         1        42         2         2
9  73566         8         2         2        56         3         3

   RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0  1.000000      1.0         1  ...       1.0       3.0       4.0
1  1.000000      2.0         1  ...       1.0       3.0       1.0
2  2.000000      1.0         1  ...       1.0       4.0       1.0
3  1.000000       25         1  ...       1.0       3.0       1.0
4  1.000000      2.0         1  ...       1.0       5.0       1.0
5  1.000000      1.0         1  ...       1.0       4.0       3.0
6  2.000000       25         1  ...       1.0       5.0       1.0
7  2.000000      2.0         1  ...       1.0       5.0       2.0
8  1.508509      2.0         1  ...       1.0       3.0       1.0
9  1.000000      2.0         1  ...       1.0       3.0       3.0

       WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2 INDFMPIR
0  13281.237386  13481.042095        1       112      4.0      4.0     0.84
1  23682.057386  24471.769625        1       108      7.0      7.0     1.78
2  57214.803319  57193.285376        1       109     10.0     10.0     4.51
3  55201.178592  55766.512438        2       109      9.0      9.0     2.52
4  63709.667069  65541.871229        2       116     15.0     15.0     5.00
5  24978.144602  25344.992359        1       111      9.0      9.0     4.79
6  18040.818432  17913.555067        1       105     15.0     15.0     5.00
7  60325.095254  61758.654880        1       114     10.0     10.0     5.00
8  23307.675629      0.000000        2       106     15.0     15.0     5.00
9  16351.783140  17480.115175        1       112      4.0      4.0     0.48

[10 rows x 38 columns]

Final DataFrame without null values:
        SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDRETH1  RIDRETH3  \
0      73557         8         2         1        69         4         4
1      73558         8         2         1        54         3         3
2      73559         8         2         1        72         3         3
3      73560         8         2         1         9         3         3
4      73561         8         2         2        73         3         3
...      ...       ...       ...       ...       ...       ...       ...
10170  83727         8         2         1        26         2         2
10171  83728         8         2         2         2         1         1
10172  83729         8         2         2        42         4         4
10173  83730         8         2         1         7         2         2
10174  83731         8         2         1        11         5         6

       RIDEXMON DMQMILIZ  DMDBORN4  ...  DMDHRBR4  DMDHREDU  DMDHRMAR  \
0           1.0      1.0         1  ...       1.0       3.0       4.0
1           1.0      2.0         1  ...       1.0       3.0       1.0
2           2.0      1.0         1  ...       1.0       4.0       1.0
3           1.0       25         1  ...       1.0       3.0       1.0
4           1.0      2.0         1  ...       1.0       5.0       1.0
...         ...      ...       ...  ...       ...       ...       ...
10170       2.0      2.0         1  ...       1.0       3.0       1.0
10171       2.0       25         1  ...       1.0       3.0       1.0
10172       2.0      2.0         2  ...       2.0       5.0       3.0
10173       1.0       25         1  ...       2.0       4.0       1.0
10174       1.0       25         1  ...       2.0       5.0       1.0

           WTINT2YR      WTMEC2YR  SDMVPSU  SDMVSTRA INDHHIN2 INDFMIN2  \
0      13281.237386  13481.042095        1       112      4.0      4.0
1      23682.057386  24471.769625        1       108      7.0      7.0
2      57214.803319  57193.285376        1       109     10.0     10.0
3      55201.178592  55766.512438        2       109      9.0      9.0
4      63709.667069  65541.871229        2       116     15.0     15.0
...             ...           ...      ...       ...      ...      ...
10170  27141.631824  28115.568221        1       104     77.0     77.0
10171  15274.475360  16512.138781        1       107      8.0      8.0
10172  24122.248900  26902.344381        1       104      7.0      7.0
10173  25521.878546  26686.025573        2       109      6.0      6.0
10174   8930.180154   9700.873491        2       106     15.0     15.0

       INDFMPIR
0      0.840000
1      1.780000
2      4.510000
3      2.520000
4      5.000000
...         ...
10170  2.252153
10171  1.950000
10172  3.660000
10173  1.050000
10174  5.000000

[10175 rows x 38 columns]